### ISSUE TITLE
RedisClientPool with timeout causing continuous protocol errors.

### ISSUE THREAD

**Issue by howardlu0106** [debasishg/scala-redis#141]
I'm currently using 3.0, creating a single RedisClientPool with timeout.  It looks like when the timeout error occurs, the pool is consistently in a bad state even when the hits to redis dramatically decreases.  Error below:

Protocol error: Got (v,[B@75106b5c) as initial reply byte
java.lang.Exception: Protocol error: Got (v,[B@75106b5c) as initial reply byte
	at com.redis.Reply$$anonfun$7.applyOrElse(RedisProtocol.scala:105)
	at com.redis.Reply$$anonfun$7.applyOrElse(RedisProtocol.scala:103)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at com.redis.Reply$$anonfun$5.applyOrElse(RedisProtocol.scala:75)
	at com.redis.Reply$$anonfun$5.applyOrElse(RedisProtocol.scala:75)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
	at com.redis.Reply$class.receive(RedisProtocol.scala:124)
	at com.redis.RedisClient.receive(RedisClient.scala:94)
	at com.redis.R$class.asList(RedisProtocol.scala:151)
	at com.redis.RedisClient.asList(RedisClient.scala:94)
	at com.redis.Operations$$anonfun$keys$1.apply(Operations.scala:50)
	at com.redis.Operations$$anonfun$keys$1.apply(Operations.scala:50)
	at com.redis.Redis$class.send(RedisClient.scala:22)
	at com.redis.RedisClient.send(RedisClient.scala:94)
	at com.redis.Operations$class.keys(Operations.scala:50)
	at com.redis.RedisClient.keys(RedisClient.scala:94)

**Comment by onilton** [comment]
This seems to affect me also. Are you using redis 3.0.x?  or 2.x ?

**Comment by debasishg** [comment]
I could not replicate the error earlier. Will look into it again. Can you please provide a failing test case ?

**Comment by onilton** [comment]
Not right now. We migrated from redis-server 2.8 to 3.0 two days ago and we are facing serious issues that seems similar to this problem. We the issue is between scala-redis 3.0 and redis-server 3.0. Right now we are going to rollback to redis-server 2.8. So I can't try to build a failing test case right now. After we rollback to 2.8 and everything goes fine, I will try to find a failing test scenario, ok? 

Thank you very much for you attention, and I will try to reply soon :)

**Comment by onilton** [comment]
It seems that the rollback from 3.0 to redis-server 2.8 went succesfully. We were suspecting that problem occurred when redis was forking the process during the (background) dump. Do you have any idea of how could I narrow down this behavior (and with this I would try to build a nice failing test case)

**Comment by iammichiel** [comment]
Same problem here. App has been up for over a week with no change in load or concurrency. When suddenly protocol errors started to appear. 

I am using a single Redis node v3 in a docker image which seems to be ok. I can access it, and get/set any information wanted. And I'm using the 3.0 version of the library.

**Comment by iammichiel** [comment]
Switching to a redis 2.8 version has not solved the problem. A protocol error has occured after one hour of up time. I am switching to a RedisConnectionPool now. Will let you know if that changes.

**Comment by debasishg** [comment]
Is it possible to have a unit test that replicates this behavior ? Any specific call that you think may give this error ?

**Comment by onilton** [comment]
I forgot to add, we are using a redisClientPool.

`val redisPool = new com.redis.RedisClientPool(redisHost, redisPort, timeout = 20000)`

**Comment by pengup** [comment]
I faced the same problem. I am using AWS Redis server (2.8) and locally Redis (2.8) in docker. The problem happened when I made a load test with multiple threading. The worst thing is that once this error happens, it won't stop, so cannot use Redis at all. 
The error happens when I am using RedisClientPool. Switching back to RedisClient seems fixing the error. Refer to https://github.com/debasishg/scala-redis/issues/109
So, what can I do if I want to use RedisClientPool? I do not have a separate test case yet to replicate the problem, but I can repeat the problem in my testing env.

**Comment by debasishg** [comment]
@pengup Can u please clarify what u mean by "load test with multiple threading" ? With `RedisClientPool` one free connection is used from the pool for every call u make. And Redis is single threaded by nature.

**Comment by debasishg** [comment]
@onilton , @iammichiel - do u face the error *only* when the system is idle for some time ? Which may be related to redis server timeouts. Can u please check if u still get the error when u disable the timeout at the server end (I think there's a parameter for that in the config file) ?

**Comment by pengup** [comment]
@debasishg I am using gatling tool (itself uses Akka Actor) for load testing. Below is my test snippet 
  object Customer {
   val payload = StringBody("""{ "email": "${email}", "password": "${password}", "ipAddress": "string" }""")
    val auth = exec(http("auth ${email} ${password}")
      .post("/authentication")
      .queryParam("api_key", apiKey)
      .body(payload).asJSON
      .check(status.is(200))
}
  val feederCustomer = csv("customers.csv").random
  val scnCustomer = scenario("Test customer").feed(feederCustomer).exec(Customer.auth)
  setUp(scnCustomer.inject(rampUsers(100).over(10 seconds))).protocols(httpConf)
I run the test locally against a local App server as well as a remote App server in AWS. In my App server side, I am using Sorted Set (Zadd, ZRANGEBYSCORE) for session management. So, when there are multiple customers threading, there could be multiple requests to Redis server simultaneously.  what could cause Protocol error? As said, using RedisClient seems fixing the problem so far. Thanks!

**Comment by debasishg** [comment]
@pengup 

> So, when there are multiple customers threading, there could be multiple requests to Redis server simultaneously.

As long as each request lands up to a separate Redis connection you should be fine. You cannot use a single connection across multiple threads. Each request needs to get a separate connection from the `RedisClientPool`.

**Comment by pengup** [comment]
@debasishg I have a Singleton object that has 
`val clients = new RedisClientPool(AppConf.cacheServerHost, AppConf.cacheServerPort)`
then, get client per request
`private def getClient(): RedisClient = {
    clients.withClient {
      client: RedisClient => client
    }
  }`
Still, I got Protocol error in this setup. Thanks!

**Comment by debasishg** [comment]
@pengup .. Does this `client` receive requests concurrently ? You mentioned Akka, so can it be the case that multiple actors use this `client` simultaneously ?

**Comment by pengup** [comment]
@debasishg I understand that each actor/thread makes separate calls, and each call will get a connection from pool. Is there any possibility to (re)use same connection from pool? Here is one example method to use `getClient()`
`  def set(key: String, value: String): Boolean = {
   getClient().set(key, value)
   }`

**Comment by debasishg** [comment]
@pengup If u want to use the same connection, then you can use a dedicated connection per actor instead of using the pool. Using the pool implies you get the next available connection. In case u r using actors, having one dedicated connection per actor makes sense since an actor processes messages sequentially

**Comment by iammichiel** [comment]
No, call to redis are made on regular basis (every x). It cannot be due to Redis-server timeouts. 
However, I was making the calls to Redis in multiple Akka actors with a single redis client. Some kind of thread-locking involved I think. Since I switched to a `RedisConnectionPool` it has not occurred once. (two weeks now up)

**Comment by pengup** [comment]
@debasishg it turned out the Protocol error is caused by concurrency issue. My load test leads concurrent access to same Redis data record. So, when I change my methods to `synchronized` calling redis, the problem disappear. So, I need to figure out how to manage concurrency issue, using `synchronized` does not sound too good, as this will slow down the performance, I guess. Any suggestion?
Still, I wonder why this problem happens only with RedisClientPool. Using RedisClient per request does not cause this problem. Could it be so that a connection keeps some data from previous requests that may cause concurrency issue in later request that uses the same connection?  Thanks!

**Comment by debasishg** [comment]
@pengup Yeah, the fact that things work ok with `synchronized` indicates some concurrency issue. I think when you are using `RedisClientPool` and getting a connection from there, multiple actors may be accessing the connection and the I/O protocol gets garbled. At the `redisclient` level nothing is stored or cached and the entire multiplexing is done by the server.

**Comment by pengup** [comment]
@debasishg I found out the problem was caused by my code using a separate method to get client, `private def getClient(): RedisClient = { clients.withClient { client => client } }` This method returns same connection all the time. A bit wondering how this happens. Now I use the way as described in README, and everything seems to work quite well. From Redis server log, I can see multiple redis client connection created. Thanks!

**Comment by debasishg** [comment]
@pengup :+1:

**Comment by matthewrj** [comment]
I am having the same problem. Redis-server: 3, scala-redis: 3.1. I'm using the RedisClientPool with multiple threads accessing the pool (using Hystrix to wrap the call). Here is how I am using it:
```
private class GetCommand(key: String) extends HystrixCommand[Option[String]](Setter
      .withGroupKey("RedisCache")
      .andCommandKey("get")) {
      override def run = clientPool.withClient {
        client => client.get(key)
      }
      override def getFallback = None
    }
```
And I get either this error:
```
java.lang.Exception: Protocol error: Got ($,[B@f56b599) as initial reply byte
	at com.redis.Reply$$anonfun$7.applyOrElse(RedisProtocol.scala:105)
	at com.redis.Reply$$anonfun$7.applyOrElse(RedisProtocol.scala:103)
 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	...
```
or this error:
```
java.lang.NumberFormatException: For input string: "20
14074,9804,9804,0.0"
 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
 	at java.lang.Integer.parseInt(Integer.java:569)
 	at java.lang.Integer.parseInt(Integer.java:615)
 	at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:272)
 	at scala.collection.immutable.StringOps.toInt(StringOps.scala:29)
 	at com.redis.serialization.Parse$Implicits$$anonfun$3.apply(Serialization.scala:38)
 	at com.redis.serialization.Parse$Implicits$$anonfun$3.apply(Serialization.scala:38)
 	at com.redis.serialization.Parse.apply(Serialization.scala:54)
``

**Comment by debasishg** [comment]
@matthewrj - Please have a look at the response of @pengup .. I suspect u r getting the same connection every time from the pool. This causes the exception.

**Comment by planetenkiller** [comment]
I can replicate this bug. You need a single `RedisClient` with `timeout` != 0 (e.g. 1).
- send  `get` in a loop
- at some point you get an `SocketTimeoutException`
- send more `get` to get " Protocol error"

note: Perform these steps in a single thread

Analysis:
`IO.readLine` does not handle `SocketTimeoutException` on the line that uses `in.read`.

From `Socket.setSoTimeout`
> If the timeout expires, a java.net.SocketTimeoutException is raised, though the Socket is still valid.

The request AFTER a `SocketTimeoutException` will get the previous response (request BEFORE `SocketTimeoutException`).


My workaround (tested):
```
     override def receive[T](pf: Reply[T]): T = {
        try {
          super.receive(pf)
        } catch {
          case ex: java.net.SocketTimeoutException =>
            // can't ignore response without a blocking socket-read so we close this socket instead
            disconnect 
            throw ex
        }
      }
```

**Comment by debasishg** [comment]
Thanks for the test case .. will take a look soon.

**Comment by debasishg** [comment]
Just now took a look .. @planetenkiller - can u please send a PR for your workaround ? I will do some testing and merge.

**Comment by planetenkiller** [comment]
@debasishg done #173
