### ISSUE TITLE
Add connection timeout setting

### ISSUE THREAD

**Issue by superduper** [debasishg/scala-redis#78]
It would be great to have ability to set connection timeout.

For instance it would be handy for hostname resolution problems(on my host almost 1 minute till java.net.ConnectException thrown). Try yourself: 

``` scala
new RedisClientPool("nonexistent", 6378)
```

**Comment by cameo99** [comment]
I believe I am having the same issue as @superduper .
If the host is down or unavailable, it will keep trying to connect until I get a java.net.ConnectException: Operation timed out.

Instead of creating a new socket with the host and port inside which I think attempts to connect automatically
https://github.com/debasishg/scala-redis/blob/b7c795098cf745517ce4088eea95358805063c86/src/main/scala/com/redis/IO.scala#L25

Would it be better to create an empty socket then use the .connect function? This way you can specify a timeout for the connection, as right now the RedisClientPool timeout is the SO_TIMEOUT.

```
val socket = new Socket()
socket.connect(new InetSocketAddress (host, port), timeout)
```
http://docs.oracle.com/javase/7/docs/api/java/net/Socket.html#connect(java.net.SocketAddress,%20int)
I use this to test the connection first, before using the RedisClientPool. It fixed the issue I was having but it would be great if this was built in to the library.

**Comment by debasishg** [comment]
I will have a look at this issue very soon. Too much swamped right now with day job and ancillary issues. Thanks for reporting.

**Comment by yaelal** [comment]
was this done ?

**Comment by debasishg** [comment]
Unfortunately no .. and it swapped out from my radar. Anyone willing to submit a PR ? Or I will take this up in the coming weekend. Should not be too difficult .. Thanks for the reminder .. I am sorry this was long overdue and I should have done it ..

**Comment by Uxio0** [comment]
I think this issue could be closed, is implemented already, right?

**Comment by debasishg** [comment]
unfortunately no .. I am heavily loaded into other activities .. care for a PR ? :-)

**Comment by Uxio0** [comment]
Done, maybe you want to squash it ;) https://github.com/debasishg/scala-redis/pull/170

**Comment by fgaule** [comment]
Is this still open?

**Comment by debasishg** [comment]
It's already implemented .. https://github.com/debasishg/scala-redis/blob/master/src/main/scala/com/redis/RedisClient.scala#L103-L105 .. I will close this issue ..
